# Generated by Django 2.2.7 on 2019-12-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191205_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prize',
            new_name='product_prize',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pub_date',
            new_name='product_pub_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='product_sub_category',
        ),
    ]
