# Generated by Django 2.2.7 on 2019-12-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ord_id', models.AutoField(primary_key=True, serialize=False)),
                ('ord_items', models.CharField(max_length=500)),
                ('ord_name', models.CharField(max_length=500)),
                ('ord_email', models.CharField(max_length=500)),
                ('ord_city', models.CharField(max_length=500)),
                ('ord_state', models.CharField(max_length=500)),
                ('ord_add1', models.CharField(max_length=500)),
                ('ord_add2', models.CharField(max_length=500)),
                ('ord_zip', models.CharField(max_length=500)),
            ],
        ),
    ]
