# Generated by Django 2.2.7 on 2019-12-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('orderUpId', models.AutoField(primary_key=True, serialize=False)),
                ('orderId', models.IntegerField(default='')),
                ('orderDisc', models.CharField(max_length=500)),
                ('orderUpTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
